/*Bölüm 23 - Yedek Alma - 
Section 23 - Backup Operations */

/*BACKUP İLE YEDEK ALMA
SCRIPT İLE YEDEK ALMA
LOG DOSYALARI İLE YEDEK ALMA
*/

--MAKING A BACKUP WITH BACKUP
--BACKUP WITH SCRIPT
--BACKUP WITH LOG FILES