/*Bölüm 6 - Aritmetik Fonksiyonlar - 
Section 6 - Arithmetic Functions
*/

--SELECT 20 + 4 AS 'Toplam', 20 - 4 AS 'Fark', 20 * 4 AS 'Çarpım', 20 / 4 AS 'Bölüm'

--SELECT * FROM TBLNOTLAR WHERE Ders = 1

--UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE Ders = 1
--SELECT * FROM TBLNOTLAR WHERE Ders = 1

--UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100
--SELECT * FROM TBLNOTLAR WHERE Ders = 1

--SELECT AVG(Ortalama) FROM TBLNOTLAR WHERE Ders = 1

-- Sınıf ortalamasının altında olan öğrencilerin "Durum2" sütunlarının yanına "Altında", aksi durumda "Üstünde" yazdıran sorguyu hazırlayın...
--SELECT OGRID, OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERS, ORTALAMA, 'Altında' AS 'Durum 2' FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
--WHERE ORTALAMA < (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS IN (1,2)
--UNION
--SELECT OGRID, OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERS, ORTALAMA, 'Üstünde' AS 'Durum 2' FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
--WHERE ORTALAMA > (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS IN (1,2)

--MATEMATİKSEL FONKSİYONLAR

--SELECT * FROM TBLNOTLAR
--ABS
--SELECT ABS(-85) AS 'MUTLAK'
--SELECT POWER(2,4) AS 'ÜS ALMA'

--SELECT POWER(SINAV1,2) FROM TBLNOTLAR

--SELECT SQRT(625) AS 'KAREKÖK'

--SELECT FLOOR(4.86) AS 'TABAN', CEILING(4.86) AS 'TAVAN'

--AVG VE SUM FONKSİYONLARI
--SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1
--SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

--SELECT DERSAD,SINAV1 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID WHERE OGRENCI=1

--SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayşe' AND OGRSOYAD = 'Çınar')

--SELECT SUM(SINAV1),AVG(SINAV1) FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayşe' AND OGRSOYAD = 'Çınar')

--Ayşe Çınar'ın Algoritma dersinde almış olduğu 1. sınav notunun sınıf ortalamasının üstünde mi yoksa altında mı olan sorguyu yapınız.
SELECT OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERSAD, SINAV1, 'Üstünde' AS 'Durum' FROM TBLNOTLAR 
INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayşe' AND OGRSOYAD = 'Çınar')
AND SINAV1 >= (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Algoritma')
UNION
SELECT OGRAD + ' ' + OGRSOYAD AS 'Ad Soyad', DERSAD, SINAV1, 'Altında' AS 'Durum' FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD = 'Ayşe' AND OGRSOYAD = 'Çınar')
AND SINAV1 < (SELECT AVG(ORTALAMA) FROM TBLNOTLAR) AND DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Algoritma')

-- Section 6 - Arithmetic Functions
--SELECT 20 + 4 AS 'Total', 20 - 4 AS 'Difference', 20 * 4 AS 'Product', 20 / 4 AS 'Quotient'

--SELECT * FROM EXAMS WHERE Course = 1

--UPDATE EXAMS SET Exam2=Exam2+10 WHERE Course = 1
--SELECT * FROM EXAMS WHERE Course = 1

--UPDATE EXAMS SET Exam2=100 WHERE Exam2>100
--SELECT * FROM EXAMS WHERE Course = 1

--SELECT AVG(Average) FROM EXAMS WHERE Course = 1

-- Query to display students whose "Status2" column indicates "Below" for those below the class average, and "Above" otherwise.
--SELECT STUDENTID, NAME + ' ' + SURNAME AS 'Full Name', COURSE, AVERAGE, 'Below' AS 'Status2' FROM EXAMS
--INNER JOIN STUDENTS ON EXAMS.STUDENT = STUDENTS.STUDENTID
--WHERE AVERAGE < (SELECT AVG(AVERAGE) FROM EXAMS) AND COURSE IN (1,2)
--UNION
--SELECT STUDENTID, NAME + ' ' + SURNAME AS 'Full Name', COURSE, AVERAGE, 'Above' AS 'Status2' FROM EXAMS
--INNER JOIN STUDENTS ON EXAMS.STUDENT = STUDENTS.STUDENTID
--WHERE AVERAGE > (SELECT AVG(AVERAGE) FROM EXAMS) AND COURSE IN (1,2)

--MATHEMATICAL FUNCTIONS

--SELECT * FROM EXAMS
--ABS
--SELECT ABS(-85) AS 'ABSOLUTE'
--SELECT POWER(2,4) AS 'POWER'

--SELECT POWER(Exam1,2) FROM EXAMS

--SELECT SQRT(625) AS 'SQUARE ROOT'

--SELECT FLOOR(4.86) AS 'FLOOR', CEILING(4.86) AS 'CEILING'

--AVG AND SUM FUNCTIONS
--SELECT SUM(Exam1) FROM EXAMS WHERE STUDENT=1
--SELECT Exam1,Course FROM EXAMS WHERE STUDENT=1

--SELECT COURSENAME,Exam1 FROM EXAMS INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID WHERE STUDENT=1

--SELECT COURSENAME,Exam1,Exam2,Exam3 FROM EXAMS INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
--WHERE STUDENT = (SELECT STUDENTID FROM STUDENTS WHERE NAME = 'Ayşe' AND SURNAME = 'Çınar')

--SELECT SUM(Exam1),AVG(Exam1) FROM EXAMS INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
--WHERE STUDENT = (SELECT STUDENTID FROM STUDENTS WHERE NAME = 'Ayşe' AND SURNAME = 'Çınar')

--Query to determine whether Ayşe Çınar's 1st exam grade in the Algorithm course is above or below the class average.
SELECT NAME + ' ' + SURNAME AS 'Full Name', COURSENAME, Exam1, 'Above' AS 'Status' FROM EXAMS 
INNER JOIN STUDENTS ON STUDENTS.STUDENTID = EXAMS.STUDENT
INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
WHERE STUDENT = (SELECT STUDENTID FROM STUDENTS WHERE NAME = 'Ayşe' AND SURNAME = 'Çınar')
AND Exam1 >= (SELECT AVG(AVERAGE) FROM EXAMS) AND COURSE = (SELECT COURSEID FROM COURSES WHERE COURSENAME = 'Algorithm')
UNION
SELECT NAME + ' ' + SURNAME AS 'Full Name', COURSENAME, Exam1, 'Below' AS 'Status' FROM EXAMS
INNER JOIN STUDENTS ON STUDENTS.STUDENTID = EXAMS.STUDENT
INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
WHERE STUDENT = (SELECT STUDENTID FROM STUDENTS WHERE NAME = 'Ayşe' AND SURNAME = 'Çınar')
AND Exam1 < (SELECT AVG(AVERAGE) FROM EXAMS) AND COURSE = (SELECT COURSEID FROM COURSES WHERE COURSENAME = 'Algorithm')