/*Bölüm 20 - Transaction - 
Section 20 Transaction*/

--TRANSACTION --> ROLLBACK COMMIT
--UPDATE TBLHESAP SET BAKIYE=BAKIYE-250 WHERE MUSTERIID=12345
--800 --> 550
--800 --> 550+250-->800
--BEGIN TRANSACTION
--INSERT INTO TBLKATEGORI (AD) VALUES ('TV')
--INSERT INTO TBLKATEGORI (AD) VALUES ('HALI')
--SELECT * FROM TBLKATEGORI
--ROLLBACK

--COMMIT
--BEGIN TRANSACTION
----INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN1',25)
----INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN2',40)
--INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN3',10)
--INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN4','B')
--SELECT * FROM TBLURUN
--COMMIT

--Section 20 Transaction
--TRANSACTION --> ROLLBACK COMMIT
--UPDATE TBLCUSTOMERACCOUNT SET BALANCE=BALANCE-250 WHERE CUSTOMERID=12345
--800 --> 550
--800 --> 550+250-->800
--BEGIN TRANSACTION
--INSERT INTO TBLCATEGORY (NAME) VALUES ('TV')
--INSERT INTO TBLCATEGORY (NAME) VALUES ('CARPET')
--SELECT * FROM TBLCATEGORY
--ROLLBACK

--COMMIT
--BEGIN TRANSACTION
----INSERT INTO TBLPRODUCT (NAME,STOCK) VALUES ('PRODUCT1',25)
----INSERT INTO TBLPRODUCT (NAME,STOCK) VALUES ('PRODUCT2',40)
--INSERT INTO TBLPRODUCT (NAME,STOCK) VALUES ('PRODUCT3',10)
--INSERT INTO TBLPRODUCT (NAME,STOCK) VALUES ('PRODUCT4','B')
--SELECT * FROM TBLPRODUCT
--COMMIT