/*Bölüm 3 - Gruplandırmalar ve Operatörler - 
Section 3 - Groupings and Operators
*/

--Bölüm 3 - Gruplandırmalar ve Operatörler
--SELECT COUNT(*) AS 'Toplam Kayıt' FROM TBLOGRENCILER
--SELECT COUNT(*) AS 'Toplam Kişi' FROM TBLOGRENCILER WHERE OGRSEHIR = 'Adana'

--SELECT SUM(SINAV1),SUM(SINAV2),SUM(SINAV3) FROM TBLNOTLAR
--SELECT AVG(SINAV1),AVG(SINAV2),AVG(SINAV3) FROM TBLNOTLAR
--SELECT MAX(SINAV1),MAX(SINAV2),MAX(SINAV3) FROM TBLNOTLAR
--SELECT MIN(SINAV1),MIN(SINAV2),MIN(SINAV3) FROM TBLNOTLAR

--SELECT OGRSEHIR,COUNT(*) AS 'Toplam' FROM TBLOGRENCILER GROUP BY OGRSEHIR
--SELECT OGRCINSIYET,COUNT(*) AS 'Toplam' FROM TBLOGRENCILER GROUP BY OGRCINSIYET

--SELECT DURUM,COUNT(*) AS 'Sonuç' FROM TBLNOTLAR GROUP BY DURUM

--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3
--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA<50
--UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTALAMA>=50

--SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP

--SELECT OGRSEHIR,COUNT(*) AS 'SAYI' FROM TBLOGRENCILER GROUP BY OGRSEHIR HAVING COUNT(*)=2

--SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP HAVING OGRKULUP = 'Kitaplık'

--Ödev: Öğrencilerin ortalamasına göre geçenler ve kalanlar
--SELECT DURUM,COUNT(*) AS 'Geçti' FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM = 1
--SELECT DURUM,COUNT(*) AS 'Kaldı' FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM = 0

--SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%a%' OR OGRSOYAD LIKE '%a%'
--SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE 'a%' AND OGRCINSIYET = 'Erkek'
--SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE 'a%' AND OGRCINSIYET = 'Kız'
--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%a%'
--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP NOT LIKE 'b%'

--SELECT DISTINCT OGRSEHIR FROM TBLOGRENCILER
--SELECT COUNT(DISTINCT(OGRSEHIR)) FROM TBLOGRENCILER

--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER
--SELECT COUNT(DISTINCT(OGRKULUP)) FROM TBLOGRENCILER

--SELECT * FROM TBLOGRENCILER ORDER BY OGRSEHIR
--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER ORDER BY OGRKULUP DESC

--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%an_%'

--SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%[N,I]'

--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP LIKE '%[k-m]'

--SELECT TOP 4 * FROM TBLOGRENCILER ORDER BY OGRID DESC

--SELECT TOP 81 PERCENT * FROM TBLOGRENCILER

--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR = 'İzmir' OR OGRSEHIR = 'Ankara' OR OGRSEHIR = 'Adana'
--SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR IN ('İzmir','Ankara','Adana')

--SELECT * FROM TBLNOTLAR WHERE SINAV1 IN (70,75,80,85,90)
--SELECT * FROM TBLNOTLAR WHERE SINAV1 NOT IN (70,75,80,85,90)

--SELECT * FROM TBLNOTLAR WHERE ORTALAMA BETWEEN 74 AND 100

SELECT * FROM TBLOGRENCILER WHERE OGRAD BETWEEN 'A' AND 'O'
SELECT * FROM TBLOGRENCILER WHERE OGRAD NOT BETWEEN 'A' AND 'N'



--Section 3 - Groupings and Operators

--SELECT COUNT(*) AS 'Total Records' FROM TBLSTUDENTS
--SELECT COUNT(*) AS 'Total People' FROM TBLSTUDENTS WHERE CITY = 'Adana'

--SELECT SUM(EXAM1), SUM(EXAM2), SUM(EXAM3) FROM TBLGRADES
--SELECT AVG(EXAM1), AVG(EXAM2), AVG(EXAM3) FROM TBLGRADES
--SELECT MAX(EXAM1), MAX(EXAM2), MAX(EXAM3) FROM TBLGRADES
--SELECT MIN(EXAM1), MIN(EXAM2), MIN(EXAM3) FROM TBLGRADES

--SELECT CITY, COUNT(*) AS 'Total' FROM TBLSTUDENTS GROUP BY CITY
--SELECT GENDER, COUNT(*) AS 'Total' FROM TBLSTUDENTS GROUP BY GENDER

--SELECT STATUS, COUNT(*) AS 'Result' FROM TBLGRADES GROUP BY STATUS

--UPDATE TBLGRADES SET AVERAGE = (EXAM1 + EXAM2 + EXAM3) / 3
--UPDATE TBLGRADES SET STATUS = 0 WHERE AVERAGE < 50
--UPDATE TBLGRADES SET STATUS = 1 WHERE AVERAGE >= 50

--SELECT CLUB, COUNT(*) FROM TBLSTUDENTS GROUP BY CLUB

--SELECT CITY, COUNT(*) AS 'COUNT' FROM TBLSTUDENTS GROUP BY CITY HAVING COUNT(*) = 2

--SELECT CLUB, COUNT(*) FROM TBLSTUDENTS GROUP BY CLUB HAVING CLUB = 'Library'

--Homework: Passed and Failed based on student averages
--SELECT STATUS, COUNT(*) AS 'Passed' FROM TBLGRADES GROUP BY STATUS HAVING STATUS = 1
--SELECT STATUS, COUNT(*) AS 'Failed' FROM TBLGRADES GROUP BY STATUS HAVING STATUS = 0

--SELECT * FROM TBLSTUDENTS WHERE NAME LIKE '%a%' OR SURNAME LIKE '%a%'
--SELECT * FROM TBLSTUDENTS WHERE NAME LIKE 'a%' AND GENDER = 'Male'
--SELECT * FROM TBLSTUDENTS WHERE NAME LIKE 'a%' AND GENDER = 'Female'
--SELECT * FROM TBLSTUDENTS WHERE CITY LIKE '%a%'
--SELECT * FROM TBLSTUDENTS WHERE CLUB NOT LIKE 'b%'

--SELECT DISTINCT CITY FROM TBLSTUDENTS
--SELECT COUNT(DISTINCT CITY) FROM TBLSTUDENTS

--SELECT DISTINCT CLUB FROM TBLSTUDENTS
--SELECT COUNT(DISTINCT CLUB) FROM TBLSTUDENTS

--SELECT * FROM TBLSTUDENTS ORDER BY CITY
--SELECT DISTINCT CLUB FROM TBLSTUDENTS ORDER BY CLUB DESC

--SELECT * FROM TBLSTUDENTS WHERE CITY LIKE '%an_%'

--SELECT * FROM TBLSTUDENTS WHERE NAME LIKE '%[N,I]'

--SELECT * FROM TBLSTUDENTS WHERE CLUB LIKE '%[k-m]'

--SELECT TOP 4 * FROM TBLSTUDENTS ORDER BY STUDENTID DESC

--SELECT TOP 81 PERCENT * FROM TBLSTUDENTS

--SELECT * FROM TBLSTUDENTS WHERE CITY = 'Izmir' OR CITY = 'Ankara' OR CITY = 'Adana'
--SELECT * FROM TBLSTUDENTS WHERE CITY IN ('Izmir', 'Ankara', 'Adana')

--SELECT * FROM TBLGRADES WHERE EXAM1 IN (70, 75, 80, 85, 90)
--SELECT * FROM TBLGRADES WHERE EXAM1 NOT IN (70, 75, 80, 85, 90)

--SELECT * FROM TBLGRADES WHERE AVERAGE BETWEEN 74 AND 100

SELECT * FROM TBLSTUDENTS WHERE NAME BETWEEN 'A' AND 'O'
SELECT * FROM TBLSTUDENTS WHERE NAME NOT BETWEEN 'A' AND 'N'
