/*Bölüm 10 - Date Sorguları - 
Section 10 - Date Queries */

--ÖRNEK DATAPART SORGULARI
--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND MUSTERI = 1

--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND 
--MUSTERI = (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR = 'Ankara')

--DATENAME FONKSİYONU
--SELECT DATENAME(MONTH,getdate()),datename(MONTH,'2019.01.15')
--SELECT DATENAME(WEEKDAY,GETDATE())
--SELECT DATENAME(WEEKDAY,'2019.06.10')

--DATEDIFF FONKSİYONU
--SELECT DATEDIFF(YEAR,'2010.10.25',GETDATE())
--SELECT DATEDIFF(MONTH,'2010.06.14','2015.08.06')
--SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBLHAREKET WHERE HAREKETID = 1

--DATEADD FONKSİYONU
--SELECT DATEADD(YEAR,3,'2009-10-25')
--SELECT DATEADD(DAY,45,GETDATE())
--SELECT DATEADD(MONTH,350,GETDATE())

--Section 10 - Date Queries
--EXAMPLE DATEPART QUERIES
--Retrieve all columns from the TBLHAREKET where the day part of TARIH is between 1 and 3 and MUSTERI is 1.
SELECT * FROM TBLHAREKET WHERE DATEPART(DAY, TARIH) BETWEEN 1 AND 3 AND MUSTERI = 1

--Retrieve all columns from TBLHAREKET where the day part of TARIH is between 1 and 3 and 
--MUSTERI is (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR = 'Ankara')
SELECT * FROM TBLHAREKET WHERE DATEPART(DAY, TARIH) BETWEEN 1 AND 3 AND 
MUSTERI = (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR = 'Ankara')

--DATENAME FUNCTION
--Retrieve the name of the month for the current date and the specified date.
SELECT DATENAME(MONTH, GETDATE()), DATENAME(MONTH, '2019.01.15')
--Retrieve the name of the weekday for the current date and a specified date.
SELECT DATENAME(WEEKDAY, GETDATE()), DATENAME(WEEKDAY, '2019.06.10')

--DATEDIFF FUNCTION
--Calculate the difference in years between two dates.
SELECT DATEDIFF(YEAR, '2010.10.25', GETDATE())
--Calculate the difference in months between two dates.
SELECT DATEDIFF(MONTH, '2010.06.14', '2015.08.06')
--Calculate the difference in days between TARIH and the current date for a specific HAREKETID.
SELECT DATEDIFF(DAY, TARIH, GETDATE()) FROM TBLHAREKET WHERE HAREKETID = 1

--DATEADD FUNCTION
--Add 3 years to the specified date.
SELECT DATEADD(YEAR, 3, '2009-10-25')
--Add 45 days to the current date.
SELECT DATEADD(DAY, 45, GETDATE())
--Add 350 months to the current date.
SELECT DATEADD(MONTH, 350, GETDATE())
