--SELECT COUNT(*) AS 'Toplam Kayıt' FROM TBLOGRENCILER
--SELECT COUNT(*) AS 'Toplam Kişi' FROM TBLOGRENCILER WHERE OGRSEHIR = 'Adana'

--SELECT SUM(SINAV1),SUM(SINAV2),SUM(SINAV3) FROM TBLNOTLAR
--SELECT AVG(SINAV1),AVG(SINAV2),AVG(SINAV3) FROM TBLNOTLAR
--SELECT MAX(SINAV1),MAX(SINAV2),MAX(SINAV3) FROM TBLNOTLAR
--SELECT MIN(SINAV1),MIN(SINAV2),MIN(SINAV3) FROM TBLNOTLAR

--SELECT OGRSEHIR,COUNT(*) AS 'Toplam' FROM TBLOGRENCILER GROUP BY OGRSEHIR
--SELECT OGRCINSIYET,COUNT(*) AS 'Toplam' FROM TBLOGRENCILER GROUP BY OGRCINSIYET