/*Bölüm 4 - İlişkili Tablolar ve Alt Sorgular -
Section 4 - Related Tables and Subqueries
*/

--UPDATE TBLOGRENCILER SET OGRKULUP=1 WHERE OGRKULUP='Bilişim'
--UPDATE TBLOGRENCILER SET OGRKULUP=2 WHERE OGRKULUP='Kitaplık'
--UPDATE TBLOGRENCILER SET OGRKULUP=3 WHERE OGRKULUP='Satranç'
--UPDATE TBLOGRENCILER SET OGRKULUP=4 WHERE OGRKULUP='Gezi'

--INSERT INTO TBLOGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) VALUES ('Berna',4,'Ankara')
--SELECT NOTID,DERSAD FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--SELECT NOTID,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--SELECT NOTID,OGRAD+ ' ' +OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR 
