/* Bölüm 8 - Genel Tekrar - 
Section 8 - General Review */

--DDL KOMUTLARI GENEL TEKRAR
--DB --> Müşteri, Ürün, Personel, Kategori, Satış
--CREATE DATABASE SatisVT
--USE SatisVT

--CREATE TABLE TBLKATEGORI
--(
--KATEGORIID tinyint identity(1,1) primary key,
--KATEGORIAD varchar(50)
--)

--CREATE TABLE TBLURUNLER
--(
--URUNID int identity(1,1) primary key,
--URUNAD varchar(50),
--URUNMARKA varchar(50),
--KATEGORI tinyint,
--URUNALISFIYAT decimal(18,2),
--URUNSATISFIYAT decimal(18,2),
--URUNSTOK smallint check(URUNSTOK>0),
--URUNDURUM bit default '1'
--)

--CREATE TABLE TBLPERSONEL
--(
--PERSONELID smallint identity(1,1) primary key,
--PERSONELADSOYAD varchar(50)
--)

--CREATE TABLE TBLMUSTERI
--(
--MUSTERIID int identity(1,1) primary key,
--MUSTERIAD varchar(50),
--MUSTERISOYAD varchar(50),
--MUSTERISEHIR varchar(14),
--MUSTERIBAKIYE decimal(18,2)
--)

--CREATE TABLE TBLHAREKET
--(
--HAREKETID int primary key identity(1,1),
--URUN int,
--MUSTERI int,
--PERSONEL smallint,
--ADET int,
--TUTAR decimal(18,2),
--TARIH smalldatetime
--)

--TRUNCATE TABLE TBLURUNLER

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BİLGİSAYAR')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EŞYA')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETİ')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')

--INSERT INTO TBLURUNLER (URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK) 
--VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)

--SELECT * FROM TBLURUNLER

--UPDATE TBLURUNLER SET URUNAD = 'SU ISITICI' WHERE URUNAD = 'KETTLE'

--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM ÜRÜN' FROM TBLURUNLER 
--INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI = TBLKATEGORI.KATEGORIID
--GROUP BY KATEGORIAD ORDER BY COUNT(*)

--KATEGORİ ADI BİLGİSAYAR OLAN ÜRÜNLERİ SATIŞ FİYATINA 500 TL ZAM YAPALIM...
--UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'BİLGİSAYAR')
--SELECT * FROM TBLURUNLER

--TV KATEGORİSİNDEKİ ÜRÜNLERİN SATIŞ FİYATINDA YÜZDE 10 İNDİRİM YAPAN SORGUYU YAZIN.
--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT - URUNSATISFIYAT * 0.10 
--WHERE KATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'TV')

--SELECT COUNT(*) AS 'KAÇ FARKLI ÜRÜN', SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER
--SELECT * FROM TBLURUNLER

--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,
--(URUNSATISFIYAT - URUNALISFIYAT) AS 'KAR',
--(URUNSATISFIYAT - URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR' FROM TBLURUNLER
--INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI = TBLKATEGORI.KATEGORIID

--TOPLAM KARI 1000 LİRANIN ALTINDA KALAN ÜRÜNLERİ SATIŞ FİYATINA YÜZDE 20 ZAM YAPAN SORGU
--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT + URUNSATISFIYAT * 0.20
--WHERE (URUNSATISFIYAT - URUNALISFIYAT) * URUNSTOK < 1000


--Section 8 - General Review 
--DDL COMMANDS GENERAL RECAP
--DB --> Customer, Product, Employee, Category, Sale
--CREATE DATABASE SalesDB
--USE SalesDB

--CREATE TABLE TBLCATEGORY
--(
--CATEGORYID tinyint identity(1,1) primary key,
--CATEGORYNAME varchar(50)
--)

--CREATE TABLE TBLPRODUCTS
--(
--PRODUCTID int identity(1,1) primary key,
--PRODUCTNAME varchar(50),
--PRODUCTBRAND varchar(50),
--CATEGORY tinyint,
--PRODUCTPURCHASEPRICE decimal(18,2),
--PRODUCTSALEPRICE decimal(18,2),
--PRODUCTSTOCK smallint check(PRODUCTSTOCK > 0),
--PRODUCTSTATUS bit default '1'
--)

--CREATE TABLE TBLEMPLOYEE
--(
--EMPLOYEEID smallint identity(1,1) primary key,
--EMPLOYEEFULLNAME varchar(50)
--)

--CREATE TABLE TBLCUSTOMER
--(
--CUSTOMERID int identity(1,1) primary key,
--CUSTOMERNAME varchar(50),
--CUSTOMERSURNAME varchar(50),
--CUSTOMERCITY varchar(14),
--CUSTOMERBALANCE decimal(18,2)
--)

--CREATE TABLE TBLTRANSACTION
--(
--TRANSACTIONID int primary key identity(1,1),
--PRODUCT int,
--CUSTOMER int,
--EMPLOYEE smallint,
--QUANTITY int,
--AMOUNT decimal(18,2),
--DATE smalldatetime
--)

--TRUNCATE TABLE TBLPRODUCTS

--INSERT INTO TBLCATEGORY (CATEGORYNAME) VALUES ('COMPUTER')
--INSERT INTO TBLCATEGORY (CATEGORYNAME) VALUES ('WHITE GOODS')
--INSERT INTO TBLCATEGORY (CATEGORYNAME) VALUES ('SMALL HOME APPLIANCE')
--INSERT INTO TBLCATEGORY (CATEGORYNAME) VALUES ('TV')

--INSERT INTO TBLPRODUCTS (PRODUCTNAME,PRODUCTBRAND,CATEGORY,PRODUCTPURCHASEPRICE,PRODUCTSALEPRICE,PRODUCTSTOCK) 
--VALUES ('REFRIGERATOR','SIEMENS',2,4356,4588,10)

--SELECT * FROM TBLPRODUCTS

--UPDATE TBLPRODUCTS SET PRODUCTNAME = 'WATER HEATER' WHERE PRODUCTNAME = 'KETTLE'

--SELECT CATEGORYNAME,COUNT(*) AS 'TOTAL PRODUCT' FROM TBLPRODUCTS 
--INNER JOIN TBLCATEGORY ON TBLPRODUCTS.CATEGORY = TBLCATEGORY.CATEGORYID
--GROUP BY CATEGORYNAME ORDER BY COUNT(*)

--INCREASE THE SALE PRICE OF PRODUCTS IN THE COMPUTER CATEGORY BY 500 TL...
--UPDATE TBLPRODUCTS SET PRODUCTSALEPRICE += 500 WHERE CATEGORY = (SELECT CATEGORYID FROM TBLCATEGORY WHERE CATEGORYNAME = 'COMPUTER')
--SELECT * FROM TBLPRODUCTS

--QUERY TO REDUCE THE SALE PRICE OF PRODUCTS IN THE TV CATEGORY BY 10%.
--UPDATE TBLPRODUCTS SET PRODUCTSALEPRICE = PRODUCTSALEPRICE - PRODUCTSALEPRICE * 0.10 
--WHERE CATEGORY = (SELECT CATEGORYID FROM TBLCATEGORY WHERE CATEGORYNAME = 'TV')

--SELECT COUNT(*) AS 'HOW MANY DIFFERENT PRODUCTS', SUM(PRODUCTSTOCK) AS 'STOCK COUNT' FROM TBLPRODUCTS
--SELECT * FROM TBLPRODUCTS

--SELECT PRODUCTID,PRODUCTNAME,PRODUCTBRAND,CATEGORYNAME,PRODUCTSALEPRICE,PRODUCTPURCHASEPRICE,PRODUCTSTOCK,
--(PRODUCTSALEPRICE - PRODUCTPURCHASEPRICE) AS 'PROFIT',
--(PRODUCTSALEPRICE - PRODUCTPURCHASEPRICE) * PRODUCTSTOCK AS 'TOTAL PROFIT' FROM TBLPRODUCTS
--INNER JOIN TBLCATEGORY ON TBLPRODUCTS.CATEGORY = TBLCATEGORY.CATEGORYID

--QUERY TO INCREASE THE SALE PRICE OF PRODUCTS WITH A TOTAL PROFIT BELOW 1000 TL.
--UPDATE TBLPRODUCTS SET PRODUCTSALEPRICE = PRODUCTSALEPRICE + PRODUCTSALEPRICE * 0.20
--WHERE (PRODUCTSALEPRICE - PRODUCTPURCHASEPRICE) * PRODUCTSTOCK < 1000
