/*Bölüm 11 - Alt Sorgu Örnekleri - 
Section 11 - Subquery Examples
*/

--ALT SORGU ÖRNEKLERİ

--SELECT URUNAD,COUNT(*) AS 'ÜRÜN AD' FROM TBLHAREKET
--INNER JOIN TBLURUNLER ON TBLHAREKET.URUN = TBLURUNLER.URUNID
--GROUP BY URUNAD ORDER BY COUNT(*)

--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE KATEGORI = 1)

--AZ ÖNCEKİ ÖRNEKTE KATEGORİ = 1 YERİNE BİLGİSAYAR OLARAK GETİREN SORGU
--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE KATEGORI = 
--(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'BİLGİSAYAR'))

--İÇ İÇE 3 SORGU
--SELECT * FROM TBLHAREKET WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR = 'ADANA')

--Beyaz eşya kategorisinde yapılan harcamaları getiren sorgu
--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE KATEGORI = 
--(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EŞYA'))

--ALT SORGULAR 3
--Adana veya Ankara'da müşterilere satılan ürünlerin toplam fiyatı
--SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ADANA' OR MUSTERISEHIR='ANKARA')

--SELECT * FROM TBLHAREKET WHERE URUN=1

--UPDATE TBLURUNLER SET URUNSTOK=URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN = 10) WHERE URUNID = 10

--KASA TABLOSU
--CREATE TABLE TBLKASA
--(
--TOPLAM decimal(18,2)
--)
--INSERT INTO TBLKASA VALUES (0)
--SELECT * FROM TBLKASA
UPDATE TBLKASA SET TOPLAM = (SELECT SUM(TUTAR) FROM TBLHAREKET)

--Section 11 - Subquery Examples
--SUBQUERY EXAMPLES

--PRODUCT COUNT PER PRODUCT
SELECT PRODUCTNAME, COUNT(*) AS 'PRODUCT COUNT' FROM TBLTRANSACTIONS
INNER JOIN TBLPRODUCTS ON TBLTRANSACTIONS.PRODUCT = TBLPRODUCTS.PRODUCTID
GROUP BY PRODUCTNAME ORDER BY COUNT(*)

--SELECT * FROM TBLTRANSACTIONS WHERE PRODUCT IN (SELECT PRODUCTID FROM TBLPRODUCTS WHERE CATEGORY = 1)

--SAME AS PREVIOUS EXAMPLE, BUT WITH CATEGORY = 1 REPLACED WITH 'COMPUTER'
SELECT * FROM TBLTRANSACTIONS WHERE PRODUCT IN (SELECT PRODUCTID FROM TBLPRODUCTS WHERE CATEGORY = 
(SELECT CATEGORYID FROM TBLCATEGORIES WHERE CATEGORYNAME = 'COMPUTER'))

--NESTED 3 SUBQUERIES
SELECT * FROM TBLTRANSACTIONS WHERE CUSTOMER IN (SELECT CUSTOMERID FROM TBLCUSTOMERS WHERE CUSTOMERCITY = 'ADANA')

--EXPENSES MADE IN WHITE GOODS CATEGORY
SELECT * FROM TBLTRANSACTIONS WHERE PRODUCT IN (SELECT PRODUCTID FROM TBLPRODUCTS WHERE CATEGORY = 
(SELECT CATEGORYID FROM TBLCATEGORIES WHERE CATEGORYNAME='WHITE GOODS'))

--SUBQUERIES 3
--TOTAL AMOUNT OF PRODUCTS SOLD TO CUSTOMERS IN ADANA OR ANKARA
SELECT SUM(AMOUNT) FROM TBLTRANSACTIONS WHERE CUSTOMER IN (SELECT CUSTOMERID FROM TBLCUSTOMERS WHERE CUSTOMERCITY='ADANA' OR CUSTOMERCITY='ANKARA')

--SELECT * FROM TBLTRANSACTIONS WHERE PRODUCT=1

--UPDATE PRODUCT STOCK
--UPDATE TBLPRODUCTS SET STOCK=STOCK-(SELECT SUM(QUANTITY) FROM TBLTRANSACTIONS WHERE PRODUCT = 10) WHERE PRODUCTID = 10

--CASH REGISTER TABLE
--CREATE TABLE TBLCASHREGISTER
--(
--    TOTAL decimal(18,2)
--)
--INSERT INTO TBLCASHREGISTER VALUES (0)
--SELECT * FROM TBLCASHREGISTER
UPDATE TBLCASHREGISTER SET TOTAL = (SELECT SUM(AMOUNT) FROM TBLTRANSACTIONS)


