/*Bölüm 21 - Fonksiyonlar - 
Section 21 - Functions
*/
--FONKSİYON OLUŞTURMA

--CREATE FUNCTION STOKARTTIR(@ADET INT)
--RETURNS INT
--AS
--BEGIN
--RETURN @ADET+26
--END
--SELECT AD,STOK,DBO.STOKARTTIR(STOK) FROM TBLURUN

--ÖDEV: BİR FONKSİYON OLUŞTURULACAK. BU FONKSİYON STOĞUN KAREKÖKÜNÜ ALACAK, ALMIŞ OLDUĞU BU KAREKÖKÜ 3 İLE ÇARPACAK.

--CREATE FUNCTION STOKKAREKOK(@STOK INT)
--RETURNS FLOAT
--AS
--BEGIN
--RETURN (SQRT(@STOK) * 3)
--END
--SELECT AD,STOK,DBO.STOKKAREKOK(STOK) FROM TBLURUN

--STRING TÜRDE FONKSİYON OLUŞTURMA
--CREATE FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR
--ALTER FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR(20)
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END

--SELECT dbo.KUCUKHARF(AD),STOK FROM TBLURUN

--KDV FONKSİYONU
--CREATE FUNCTION KDV(@FIYAT DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN @FIYAT * 1.18
--END
--SELECT AD,SATISFIYAT,dbo.KDV(SATISFIYAT) AS 'KDVLİ HALİ' FROM TBLURUN

--TABLO SONUÇLU FONKSİYONLAR
--CREATE FUNCTION URUNBILGI(@URID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE URUNID = @URID
--SELECT * FROM dbo.URUNBILGI(4)

--ÖDEV: STOK SAYISINI GİRDİĞİNİZ ZAMAN BU STOK SAYISININ ALTINDA OLAN ÜRÜNLERİ GETİREN FONKSİYONU YAZIN.
--CREATE FUNCTION STOKSAYISIALTI(@SAYI INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE STOK <= @SAYI
--SELECT * FROM dbo.STOKSAYISIALTI(50)

--Section 21 - Functions
--FUNCTION CREATION

--CREATE FUNCTION INCREASESTOCK(@QUANTITY INT)
--RETURNS INT
--AS
--BEGIN
--RETURN @QUANTITY + 26
--END
--SELECT NAME, STOCK, DBO.INCREASESTOCK(STOCK) FROM TBLPRODUCT

--ASSIGNMENT: CREATE A FUNCTION. THIS FUNCTION WILL TAKE THE SQUARE ROOT OF THE STOCK, THEN MULTIPLY THE RESULT BY 3.

--CREATE FUNCTION STOCKSQUAREROOT(@STOCK INT)
--RETURNS FLOAT
--AS
--BEGIN
--RETURN (SQRT(@STOCK) * 3)
--END
--SELECT NAME, STOCK, DBO.STOCKSQUAREROOT(STOCK) FROM TBLPRODUCT

--STRING-TYPE FUNCTION CREATION
--CREATE FUNCTION LOWERCASE(@NAME VARCHAR(20))
--RETURNS VARCHAR
--ALTER FUNCTION LOWERCASE(@NAME VARCHAR(20))
--RETURNS VARCHAR(20)
--AS
--BEGIN
--RETURN LOWER(@NAME)
--END

--SELECT dbo.LOWERCASE(NAME), STOCK FROM TBLPRODUCT

--VAT FUNCTION
--CREATE FUNCTION VAT(@PRICE DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN @PRICE * 1.18
--END
--SELECT NAME, SALESPRICE, dbo.VAT(SALESPRICE) AS 'WITH VAT' FROM TBLPRODUCT

--TABLE-VALUED FUNCTIONS
--CREATE FUNCTION PRODUCTINFO(@PRODID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLPRODUCT WHERE PRODUCTID = @PRODID
--SELECT * FROM dbo.PRODUCTINFO(4)

--ASSIGNMENT: WRITE A FUNCTION THAT BRINGS PRODUCTS BELOW A GIVEN STOCK WHEN YOU ENTER THE STOCK NUMBER.
--CREATE FUNCTION STOCKBELOW(@NUMBER INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLPRODUCT WHERE STOCK <= @NUMBER
--SELECT * FROM dbo.STOCKBELOW(50)