/*Bölüm 4 - İlişkili Tablolar ve Alt Sorgular -
Section 4 - Related Tables and Subqueries
*/

--UPDATE TBLOGRENCILER SET OGRKULUP=1 WHERE OGRKULUP='Bilişim'
--UPDATE TBLOGRENCILER SET OGRKULUP=2 WHERE OGRKULUP='Kitaplık'
--UPDATE TBLOGRENCILER SET OGRKULUP=3 WHERE OGRKULUP='Satranç'
--UPDATE TBLOGRENCILER SET OGRKULUP=4 WHERE OGRKULUP='Gezi'

--INSERT INTO TBLOGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) VALUES ('Berna',4,'Ankara')
--SELECT NOTID,DERSAD FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--SELECT NOTID,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--SELECT NOTID,OGRAD+ ' ' +OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR 
--INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID

--Ödev: Az önceki örnekten faydalanarak Durum 1 olanları Geçti, 0 olanları Kaldı yazsın.
--SELECT NOTID,OGRAD+' '+OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,
--CASE WHEN DURUM = 1 THEN 'Geçti' ELSE 'Kaldı' END AS 'SONUÇ' FROM TBLNOTLAR
--INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID

--SELECT * FROM TBLNOTLAR
--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1
--UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTALAMA >= 50
--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA < 50

--Dersler tablosunda ismi matematik olan derse ait sınav not bilgisi
-- SUB QUERY
--SELECT * FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Matematik')

--Dersler tablosunda ismi algoritma olan notlar tablosundaki algoritma dersine ait en yüksek sınav1'i getiren sorgu
--SELECT MAX(SINAV1) FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD = 'Algoritma')
-- Daha kapsamlı örnek
SELECT NOTID,OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1 AS 'En yüksek SINAV1 notu' FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
WHERE SINAV1 = (SELECT MAX(SINAV1) FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD='Algoritma'))


--Section 4 - Related Tables and Subqueries
-- Update student clubs
UPDATE STUDENTS SET CLUB=1 WHERE CLUB='IT'
UPDATE STUDENTS SET CLUB=2 WHERE CLUB='Library'
UPDATE STUDENTS SET CLUB=3 WHERE CLUB='Chess'
UPDATE STUDENTS SET CLUB=4 WHERE CLUB='Travel'

-- Insert a new student record
INSERT INTO STUDENTS (NAME, CLUB, CITY) VALUES ('Berna', 4, 'Ankara')

-- Join tables to display grades, including student and course information
SELECT GRADEID, COURSENAME FROM EXAMS INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
SELECT GRADEID, COURSENAME, EXAM1, EXAM2, EXAM3, AVERAGE, STATUS FROM EXAMS INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
SELECT GRADEID, NAME+ ' ' +SURNAME AS 'NAME SURNAME', COURSENAME, EXAM1, EXAM2, EXAM3, AVERAGE, STATUS FROM EXAMS 
INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
INNER JOIN STUDENTS ON EXAMS.STUDENT = STUDENTS.STUDENTID

-- Display results with Pass/Fail based on the STATUS column
SELECT GRADEID, NAME+' '+SURNAME AS 'NAME SURNAME', COURSENAME, EXAM1, EXAM2, EXAM3, AVERAGE,
CASE WHEN STATUS = 1 THEN 'Passed' ELSE 'Failed' END AS 'RESULT' FROM EXAMS
INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
INNER JOIN STUDENTS ON EXAMS.STUDENT = STUDENTS.STUDENTID

-- Update grades and status in the EXAMS table
UPDATE EXAMS SET AVERAGE=(EXAM1+EXAM2+EXAM3)/3 WHERE COURSE=1
UPDATE EXAMS SET STATUS=1 WHERE AVERAGE >= 50
UPDATE EXAMS SET STATUS=0 WHERE AVERAGE < 50

-- Subquery to retrieve grades for the 'Math' course from the COURSES table
SELECT * FROM EXAMS WHERE COURSE = (SELECT COURSEID FROM COURSES WHERE COURSENAME = 'Math')

-- Subquery to retrieve the highest EXAM1 for the 'Algorithm' course from the EXAMS table
SELECT MAX(EXAM1) FROM EXAMS WHERE COURSE = (SELECT COURSEID FROM COURSES WHERE COURSENAME = 'Algorithm')
-- A more comprehensive example
SELECT GRADEID, NAME + ' ' + SURNAME AS 'NAME SURNAME', COURSENAME, EXAM1 AS 'Highest EXAM1 grade' FROM EXAMS
INNER JOIN STUDENTS ON EXAMS.STUDENT = STUDENTS.STUDENTID
INNER JOIN COURSES ON EXAMS.COURSE = COURSES.COURSEID
WHERE EXAM1 = (SELECT MAX(EXAM1) FROM EXAMS WHERE COURSE = (SELECT COURSEID FROM COURSES WHERE COURSENAME='Algorithm'))
